// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"
)

type Account struct {
	ID        string
	OwnerName string
	Balance   int64
	Number    string
	BankID    string
	CreatedAt time.Time
}

type Bank struct {
	ID        string
	Code      string
	Name      string
	CreatedAt time.Time
}

type PixKey struct {
	ID        string
	Kind      string
	Key       string
	Status    string
	AccountID string
	CreatedAt time.Time
}

type Transaction struct {
	ID            string
	AccountFromID string
	PixKeyID      string
	Amount        int64
	CreatedAt     time.Time
}
